#!/bin/sh

rm -f csh-out shell-out
echo "Test12: Enviroment: Redirect printenv"
echo "/usr/bin/printenv | grep PATH" > csh-in

#Make sure that printenv is a built in command
PATH=/bin
export PATH
echo "printenv | grep PATH" > shell-in

../shell < shell-in > shell-out
/bin/sh < csh-in > csh-out
sort -n shell-out > shell-out-sort
sort -n csh-out > csh-out-sort
/usr/bin/diff shell-out-sort csh-out-sort
if [ $? -ne 0 ]
then
    echo "Test12 failed"
    exit -1
fi
echo Test12 OK
exit 0
